### ISSUE TITLE
New navigation

### ISSUE THREAD

**Issue by maticoblak** [ZanJereb/testing#9]
We want to add a bit more screen navigation to the application. You will keep the main screen for loading and then present the current my cast screen non animated. The button from the first screen will be removed and only the background will be used the same as from my cast screen. The second screen will be a navigation controller with the ability to add a new cast.

- [x] Modify the main screen to show background #10 
- [x] Modify the casts screen to have navigation controller #11
- [x] Create navigation to the Add cast controller #12
